# Autor: Cristtopher Quintana T. <cquintana@axxezo.com>
image: node:boron

pipelines:
  default:
    - step:
        caches:
          - node
        script:
            - npm install
            #- npm test
            - docker login axxezo.azurecr.io -u axxezo -p Gp/THWeHCoql15kUZdig88PFf5oRWM8g
            - docker build -t axxezo.azurecr.io/unwp-backend .
            - docker push axxezo.azurecr.io/unwp-backend
options:
  docker: true