# Autor: Cristtopher Quintana T. <cquintana@axxezo.com>
image: node:boron

pipelines:
  default:
    - step:
        caches:
          - node
        script:
            - npm install --global gulp
            - npm install
  branches:
    master:
      - step:
         script:
            - gulp build
            - export NODE_ENV=production
            #- npm test
            - docker login axxezo.azurecr.io -u axxezo -p Gp/THWeHCoql15kUZdig88PFf5oRWM8g
            - docker build -t axxezo.azurecr.io/unwp-backend:v1 .
            - docker push axxezo.azurecr.io/unwp-backend:v1
options:
  docker: true
