# Autor: Cristtopher Quintana T. <cquintana@axxezo.com>
image: node:boron

pipelines:
  default:
    - step:
        caches:
          - node
        script:
            - node -v
            - npm install
            - npm install -g gulp
            #- npm test
  # Only on the main branch 
  # push & build image to the container registry
  branches:
    master:
       - step:
          script:
            - npm install
            - npm install -g gulp
            - npm install gulp --save-dev
            - export NODE_ENV=production
            - export PORT=5001
            - gulp build
            #- npm test
            - docker login axxezo.azurecr.io -u axxezo -p Gp/THWeHCoql15kUZdig88PFf5oRWM8g
            - docker build -t axxezo.azurecr.io/unwp-backend:v1 .
            - docker push axxezo.azurecr.io/unwp-backend:v1
options:
  docker: true
